name: Deploy Resume Analyzer
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Lambda using AWS CLI
        run: |
          zip -r textractHandler.zip lambda/textractHandler.js
          aws lambda update-function-code --function-name textractLambda --zip-file fileb://textractHandler.zip


